language: r
sudo: false
os:
#  - osx
  - linux
cache:
  packages: true
r: bioc-devel
r_github_packages:
  - jimhester/covr
before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix
after_success:
  - Rscript -e 'covr::codecov()'
