language: r
sudo: false
dist: trusty
cache: packages
r: bioc-devel
r_github_packages:
  - jimhester/covr
before_install:
  - apt-get install texlive-fonts-extra
after_success:
  - Rscript -e 'covr::codecov()'
